### ISSUE TITLE
Text cutoff in KTitleWidget

### ISSUE THREAD

**Issue by beojan** [luebking/virtuality#26]
It appears that the descenders on the bottom line of text in the titlewidget is sometimes cutoff

![font-rendering-problem-wtcurve2](https://cloud.githubusercontent.com/assets/3727925/7372497/f4485d50-edbe-11e4-8ce3-cf5e449ba1f9.png)

This problem also existed with Bespin, but I can't find the report now, so I may not have reported it.

**Comment by luebking** [comment]
should be fixed with commit 98ab4fa1744fda00f5a5827a4537d815ad70804a

**Comment by beojan** [comment]
Not quite, part of the descender is still cut off
![font-rendering-problem-wtcurve2](https://cloud.githubusercontent.com/assets/3727925/7387959/71d822a6-ee59-11e4-9152-f4fb8df42be5.png)

As you can see, the descender on the g is a straight line because part of it is cut off.

**Comment by luebking** [comment]
I saw your comment, but despite my legal issue with the universe, the day still has only 24h ;-P

You should btw. be able to re-open your own bugs?

**Comment by beojan** [comment]
Apparently only if I closed it, not if you closed it.

**Comment by beojan** [comment]
Still not fixed. The text is just bigger now
![font-rendering-problem-wtcurve2](https://cloud.githubusercontent.com/assets/3727925/7436913/2681abe0-f04a-11e4-9573-4433cfe2184d.png)

**Comment by luebking** [comment]
Qt4 or Qt5
Which font size?
Which hinting (auto, strength)?
Subpixel rendering?
What dpi has the system ("xdpyinfo | grep resolution")?

**Comment by beojan** [comment]
I noticed it on Qt4, but it may also exist on Qt5.

Font size: 9pt
Hinting slight, and I think it has truetype hints

Subpixel rendering : RGB

1920×1080 on a 15.6 in screen (not currently at my laptop)

Sincerely,
Beojan Stanislaus

**Comment by luebking** [comment]
On Freitag, 1. Mai 2015 23:21:45 CEST, Beojan Stanislaus wrote:
> I noticed it on Qt4, but it may also exist on Qt5.
Native or raster graphicssystem?

(in doubt, check for differences w/ "--graphicssystem raster" and "--graphicssystem native", the KWin setting doesn't matter)

> 1920×1080 on a 15.6 in screen (not currently at my laptop)
ie. should be 146 dpi - this can indeed be a cause, because the hinters act largely different on HiRes screens. I assume the boundingrect ./. tight bounding rect calculation difference will narrow.

If you don't mind, in hacks.cpp:426 you'll find

   f = qMin(f, (r.height()+(br.height()-r.height())/3.0f)/br.height());

Try instead

   f = qMin(f, (r.height()/br.height());

and if that works sth. along

   f = qMin(f, (r.height()+(br.height()-r.height())/5.0f)/br.height());

ie. increase the number.

**Comment by beojan** [comment]
Changing to 
```
   f = qMin(f, (float)r.height()/br.height());
```
fixes the issue, and the text isn't too big either.
